DROP TYPE IF EXISTS kind_of_type;
CREATE TYPE kind_of_type AS ENUM (
    'preloaded',
    'user_added'
);

CREATE TABLE users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fname TEXT NOT NULL,
    lname TEXT NOT NULL,
    username TEXT NOT NULL,
    password VARCHAR NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
    );
