DROP TYPE IF EXISTS kind_of_type;
CREATE TYPE kind_of_type AS ENUM (
    'preloaded',
    'user_added'
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fname TEXT NOT NULL,
    lname TEXT NOT NULL,
    username TEXT NOT NULL,
    password VARCHAR NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    ishandicap BOOLEAN DEFAULT false,
    isfamily BOOLEAN DEFAULT false,
    hasstalls BOOLEAN DEFAULT false,
    isprivate BOOLEAN DEFAULT false,
    gender_neutral BOOLEAN DEFAULT false,
    hasbaby_table BOOLEAN DEFAULT false,

);


-- CREATE TABLE favorites (
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     bathroom_id VARCHAR
--         REFERENCES bathrooms(id) ON DELETE CASCADE NOT NULL,
--     user_id INTEGER
--         REFERENCES users(id) ON DELETE CASCADE NOT NULL
-- );

-- CREATE TABLE comments (
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
--     text TEXT NOT NULL,
--     date_commented TIMESTAMPTZ DEFAULT now() NOT NULL,
--     bathroom_id VARCHAR
--         REFERENCES bathrooms(id) ON DELETE CASCADE NOT NULL,
--     user_id INTEGER
--         REFERENCES users(id) ON DELETE CASCADE NOT NULL
-- );

-- DROP TYPE IF EXISTS rate_category;
-- CREATE TYPE rate_category AS ENUM (
--     'Cleanliness',
--     'Privacy',
--     'Overall',
--     'Accessibility'
-- );

-- CREATE TABLE rates (
--     bathroom_id VARCHAR
--         REFERENCES bathrooms(id) ON DELETE CASCADE NOT NULL,
--     rate_category rate_category NOT NULL,
--     rating INTEGER NOT NULL,
--     user_id INTEGER
--         REFERENCES users(id) ON DELETE CASCADE NOT NULL
-- );

-- DROP TYPE IF EXISTS tag;
-- CREATE TYPE tag AS ENUM (
--     'Handicap Accessibile',
--     'Family',
--     'Stalls',
--     'Private',
--     'Gender Neutral',
--     'Baby Changing Table'
-- );

-- CREATE TABLE tags (
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     bathroom_id VARCHAR
--     REFERENCES bathrooms(id) ON DELETE CASCADE NOT NULL,
--     tag tag NOT NULL
-- );