CREATE TABLE favorites (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bathroom_id VARCHAR
        REFERENCES bathrooms(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    text TEXT NOT NULL,
    date_commented TIMESTAMPTZ DEFAULT now() NOT NULL,
    bathroom_id VARCHAR
        REFERENCES bathrooms(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

DROP TYPE IF EXISTS rate_category;
CREATE TYPE rate_category AS ENUM (
    'Cleanliness',
    'Privacy',
    'Overall',
    'Accessibility'
);

CREATE TABLE rates (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bathroom_id VARCHAR
        REFERENCES bathrooms(id) ON DELETE CASCADE NOT NULL,
    rating INTEGER NOT NULL,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

-- DROP TYPE IF EXISTS tag;
-- CREATE TYPE tag AS ENUM (
--     'Handicap Accessible',
--     'Family',
--     'Stalls',
--     'Private',
--     'Gender Neutral',
--     'Baby Changing Table'
-- );

-- CREATE TABLE tags (
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     bathroom_id VARCHAR
--     REFERENCES bathrooms(id) ON DELETE CASCADE NOT NULL,
--     tag tag NOT NULL
-- );